### PR TITLE
Some fixes for the stale_package_check function

### PR DESCRIPTION
**Pull request by SarenT**

### CODE REVIEW

**Comment by MichaelChirico** [comment]
Thanks so much for this! 

I'll go ahead and merge but actually a better approach would be to use AST rather than regex

**Comment by SarenT** [comment]
I guess so. This was a quick fix on my part :)

**Comment by SarenT** [comment]
Thanks for providing the function in the first place. It saved a lot of time for me :)

**Comment by MichaelChirico** [comment]
@SarenT check latest master -- I've added a more sophisticated version of `stale_package_check`

**Pull request merged**
